import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  suppressHydrationWarning={true}>
      <body
        className={`antialiased`}
      >
        <SidebarProvider style={{position: 'relative'}}>
          <AppSidebar />
          <main style={{position: 'relative', width: 'inherit'}}>
          <SidebarTrigger style={{position: 'absolute'}}/>
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
